<?php

/**
 * Implements hook_form_alter().
 */

function custom_js_scripts_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Check if the form is a webform.
  if (strpos($form_id, 'webform_submission_static_data_publication_log_shee_add_form') === 0) {
    // Get the current page of the webform.
    $current_page = $form_state->get('current_page'); 

//dpm($current_page, 'current_page');  //Edd devel modul first

    // Attach the corresponding library based on the page.
    switch ($current_page) {
      case 'receipt_and_assessment':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_receipt_and_assessment';
        break;

      case 'evaluation':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_evaluation';
        break;

      case 'sdo_db':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_sdo_db';
        break;

      case 'aimdb':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_aimdb';
        break;              

      case 'charting':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_charting';
        break; 

      case 'contact_with_data_originator':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_contact_with_data_originator';
        break; 

      case 'remarks':
        $form['#attached']['library'][] = 'custom_js_scripts/custom_js_scripts_remarks';
        break; 

      default:
        break;
    }
  }
}

