<?php

/**
 * Alter webform elements.
 *
 * @param array $element
 *   The webform element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param array $context
 *   An associative array containing the following key-value pairs:
 *   - form: The form structure to which elements is being attached.
 */

function log_sheet_number_webform_element_alter(array &$element, \Drupal\Core\Form\FormStateInterface $form_state, array $context) {
  // Check if the current element is one of the elements you want to alter.
  $webform_ids_to_alter = [
    'static_data_publication_log_shee--log_sheet_number_evaluator',
    'static_data_publication_log_shee--log_sheet_number_evaluator2',
    'static_data_publication_log_shee--log_sheet_number_sdo_db',
    'static_data_publication_log_shee--log_sheet_number_aimdb',
    'static_data_publication_log_shee--log_sheet_number_charting',
    'static_data_publication_log_shee--log_sheet_number_rdr',
    'static_data_publication_log_shee--log_sheet_number_evel',
    'static_data_publication_log_shee--log_sheet_number_did',
    'static_data_publication_log_shee--log_sheet_number_cc'

  ];
  if (isset($element['#webform_id']) && in_array($element['#webform_id'], $webform_ids_to_alter)) {
    $value_entered = $form_state->getValue('log_sheet_number');
    //dpm($value_entered, 'value_entered');
    $element['#default_value'] = $value_entered;
    $element['#attributes']['readonly'] = 'readonly';
  }
}


